#!/bin/sh

case "$1" in
  start)
    echo "Starting Tor..."
    start-stop-daemon -S -c tor -x /usr/bin/tor -- -f /etc/tor/torrc
    ;;
  stop)
    echo "Stopping Tor..."
    killall tor
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
